// definitionWords.js

export const definitionWords = [
  "define",
  "define a",
  "definition of",
  "what is",
  "what's",
  "what's a",
  "what is a",
  "how to",
  "explain",
  "meaning of",
  "describe",
  "tell me about",
  "give me info on",
  "information about",
  "what are",
  "who is",
  "who's",
  "who are",
  "where is",
  "where's",
  "where are",
  "when is",
  "when's",
  "when are",
  "why is",
  "why's",
  "why are",
  "which is",
  "which are",
  "list of",
  "examples of",
  "types of",
  "kinds of",
  "ways to",
  "steps to",
  "methods to",
  "techniques to",
  "tips to",
  "guidelines for",
  "rules for",
  "principles of",
  "facts about",
  "information on",
  "details on",
  "history of",
  "origin of",
  "background of",
  "purpose of",
  "role of",
  "function of",
  "uses of",
  "advantages of",
  "benefits of",
  "disadvantages of",
  "limitations of",
  "pros and cons of",
  "importance of",
  "significance of",
  "impact of",
  "effects of",
  "definition",
  "definition for",
  "meaning",
  "meaning for",
  "explanation of",
  "description of",
  "overview of",
  "summary of",
  "introduction to",
  "guide to",
  "manual for",
  "tutorial on",
  "steps for",
  "how does",
  "how do",
  "how can",
  "how to use",
  "how to make",
  "how to create",
  "how to build",
  "how to learn",
  "how to improve",
  "how to understand",
  "how to explain",
  "how to describe",
  "how to define",
  "how to solve",
  "how to implement",
  "how to apply",
  "how to study",
  "how to practice",
  "how to teach",
  "what do",
  "what does",
  "what can",
  "which do",
  "which does",
  "which can",
  "tell me what",
  "tell me how",
  "give me details on",
  "give me info about",
  "basic info on",
  "simple definition of",
  "short meaning of",
  "full explanation of",
  "detailed explanation of",
  "easy explanation of",
  "simple description of",
  "brief description of",
  "quick guide to",
  "complete guide to",
  "all about",
  "information for",
  "facts for",
  "knowledge about",
  "everything about",
  "overview for",
  "summary for",
  "key points on",
  "main points on",
  "step by step guide on",
  "step by step explanation",
  "list examples of",
  "examples for",
  "cases of",
  "real world examples of",
  "practical examples of",
  "applications of",
  "uses for",
  "methods for",
  "techniques for",
  "ways for",
  "tips for",
  "how to do",
  "how it works",
  "how it is done",
  "how it is used",
  "how it functions",
  "how to apply",
  "how to implement",
  "why it is important",
  "why it matters",
  "reasons for",
  "benefits for",
  "advantages for",
  "disadvantages for",
  "problems with",
  "challenges of",
  "common mistakes in",
  "key terms in",
  "terminology of",
  "definitions of key terms",
  "meanings of terms",
  "full meaning of",
  "short meaning for",
  "basic guide to",
  "beginner guide to",
  "complete information on",
  "full details on",
  "intro to",
  "basics of",
  "fundamentals of",
  "principles for",
  "main concepts of",
  "core concepts of",
  "essential facts about",
  "important things about",
  "things to know about",
  "quick facts on",
  "quick info on",
  "summary of facts on",
  "history for",
  "origin for",
  "background info on",
  "historical facts about",
  "historical background of",
  "meaning behind",
  "purpose behind",
  "reason behind",
  "definition behind",
  "details about",
  "key facts about",
  "interesting facts about",
  "informative facts on",
  "tips and tricks for",
  "do's and don'ts of",
  "guide for beginners",
  "guide for students",
  "guide for professionals",
  "guide for teachers",
  "simple guide on",
  "basic steps for",
  "easy steps to",
  "how to master",
  "how to understand better",
  "how to explain clearly",
  "how to describe well",
  "how to summarize",
  "how to analyze",
  "how to evaluate",
  "how to review",
  "how to assess",
  "how to learn fast",
  "how to practice effectively",
  "what is the function of",
  "what is the role of",
  "what is the meaning of",
  "what is the purpose of",
  "which one is",
  "which type of",
  "which kind of",
  "examples include",
  "sample examples of",
  "illustrations of",
  "case studies of",
  "details regarding",
  "information regarding",
  "facts regarding",
  "insights on",
  "understanding of",
  "knowledge of",
  "comprehensive guide to",
  "full explanation for",
  "complete overview of",
  "complete description of",
  "things you need to know about",
  "most important facts about",
  "main ideas of",
  "critical points of",
  "key elements of",
  "fundamental principles of",
  "basic concepts of",
  "core ideas of",
  "practical tips on",
  "expert advice on",
  "step by step tutorial on",
  "learning guide for",
  "how to explain to someone",
  "simple steps for",
  "easy way to",
  "shortcut to",
  "how to remember",
  "common questions about",
  "frequently asked questions about",
  "tricks for",
  "techniques to",
  "ways to improve",
  "ways to learn",
  "ways to teach",
  "ways to understand",
  "ways to explain",
  "ways to describe",
  "ways to define",
  "ways to solve",
  "ways to implement",
  "ways to apply",
  "ways to analyze",
  "ways to study",
  "ways to practice",
  "useful information on",
  "detailed facts about",
  "complete information for",
  "everything you should know about",
  "step by step guide for",
  "stepwise explanation of",
  "full tutorial on",
  "detailed guide to",
  "how to approach",
  "how to handle",
  "how to deal with",
  "how to overcome",
  "common problems in",
  "frequent issues with",
  "typical mistakes in",
  "usual errors in",
  "main challenges in",
  "critical issues in",
  "common misconceptions about",
  "important tips for",
  "practical advice on",
  "expert tips on",
  "step by step method for",
  "full method to",
  "complete method to",
  "complete instructions for",
  "detailed instructions for",
  "how to execute",
  "how to perform",
  "how to run",
  "how to organize",
  "how to structure",
  "how to plan",
  "how to design",
  "how to develop",
  "how to prepare",
  "how to implement effectively",
  "best practices for",
  "recommended steps for",
  "recommended method to",
  "stepwise guide to",
  "easy guide to",
  "simple explanation for",
  "detailed overview of",
  "full overview of",
  "complete overview for"
];
