// definitionWords.js

export const definitionWords = [
  "define",
  "define a",
  "definition of",
  "what is",
  "what's",
  "what's a",
  "what is a",
  "how to",
  "explain",
  "meaning of",
  "describe",
  "tell me about",
  "give me info on",
  "information about",
  "what are",
  "who is",
  "who's",
  "who are",
  "where is",
  "where's",
  "where are",
  "when is",
  "when's",
  "when are",
  "why is",
  "why's",
  "why are",
  "which is",
  "which are",
  "list of",
  "examples of",
  "types of",
  "kinds of",
  "ways to",
  "steps to",
  "methods to",
  "techniques to",
  "tips to",
  "guidelines for",
  "rules for",
  "principles of",
  "facts about",
  "information on",
  "details on",
  "history of",
  "origin of",
  "background of",
  "purpose of",
  "role of",
  "function of",
  "uses of",
  "advantages of",
  "benefits of",
  "disadvantages of",
  "limitations of",
  "pros and cons of",
  "importance of",
  "significance of",
  "impact of",
  "effects of",
  "definition",
  "definition for",
  "meaning",
  "meaning for",
  "explanation of",
  "description of",
  "overview of",
  "summary of",
  "introduction to",
  "guide to",
  "manual for",
  "tutorial on",
  "steps for",
  "how does",
  "how do",
  "how can",
  "how to use",
  "how to make",
  "how to create",
  "how to build",
  "how to learn",
  "how to improve",
  "how to understand",
  "how to explain",
  "how to describe",
  "how to define",
  "how to solve",
  "how to implement",
  "how to apply",
  "how to study",
  "how to practice",
  "how to teach",
  "what do",
  "what does",
  "what can",
  "which do",
  "which does",
  "which can",
  "tell me what",
  "tell me how",
  "give me details on",
  "give me info about",
  "basic info on",
  "simple definition of",
  "short meaning of",
  "full explanation of",
  "detailed explanation of",
  "easy explanation of",
  "simple description of",
  "brief description of",
  "quick guide to",
  "complete guide to",
  "all about",
  "information for",
  "facts for",
  "knowledge about",
  "everything about",
  "overview for",
  "summary for",
  "key points on",
  "main points on",
  "step by step guide on",
  "step by step explanation",
  "list examples of",
  "examples for",
  "cases of",
  "real world examples of",
  "practical examples of",
  "applications of",
  "uses for",
  "methods for",
  "techniques for",
  "ways for",
  "tips for",
  "how to do",
  "how it works",
  "how it is done",
  "how it is used",
  "how it functions",
  "how to apply",
  "how to implement",
  "why it is important",
  "why it matters",
  "reasons for",
  "benefits for",
  "advantages for",
  "disadvantages for",
  "problems with",
  "challenges of",
  "common mistakes in",
  "key terms in",
  "terminology of",
  "definitions of key terms",
  "meanings of terms",
  "full meaning of",
  "short meaning for",
  "basic guide to",
  "beginner guide to",
  "complete information on",
  "full details on",
  "intro to",
  "basics of",
  "fundamentals of",
  "principles for",
  "main concepts of",
  "core concepts of",
  "essential facts about",
  "important things about",
  "things to know about",
  "quick facts on",
  "quick info on",
  "summary of facts on",
  "history for",
  "origin for",
  "background info on",
  "historical facts about",
  "historical background of",
  "meaning behind",
  "purpose behind",
  "reason behind",
  "definition behind",
  "details about",
  "key facts about",
  "interesting facts about",
  "informative facts on",
  "tips and tricks for",
  "do's and don'ts of",
  "guide for beginners",
  "guide for students",
  "guide for professionals",
  "guide for teachers",
  "simple guide on",
  "basic steps for",
  "easy steps to",
  "how to master",
  "how to understand better",
  "how to explain clearly",
  "how to describe well",
  "how to summarize",
  "how to analyze",
  "how to evaluate",
  "how to review",
  "how to assess",
  "how to learn fast",
  "how to practice effectively",
  "what is the function of",
  "what is the role of",
  "what is the meaning of",
  "what is the purpose of",
  "which one is",
  "which type of",
  "which kind of",
  "examples include",
  "sample examples of",
  "illustrations of",
  "case studies of",
  "details regarding",
  "information regarding",
  "facts regarding",
  "insights on",
  "understanding of",
  "knowledge of",
  "comprehensive guide to",
  "full explanation for",
  "complete overview of",
  "complete description of",
  "things you need to know about",
  "most important facts about",
  "main ideas of",
  "critical points of",
  "key elements of",
  "fundamental principles of",
  "basic concepts of",
  "core ideas of",
  "practical tips on",
  "expert advice on",
  "step by step tutorial on",
  "learning guide for",
  "how to explain to someone",
  "simple steps for",
  "easy way to",
  "shortcut to",
  "how to remember",
  "common questions about",
  "frequently asked questions about",
  "tricks for",
  "techniques to",
  "ways to improve",
  "ways to learn",
  "ways to teach",
  "ways to understand",
  "ways to explain",
  "ways to describe",
  "ways to define",
  "ways to solve",
  "ways to implement",
  "ways to apply",
  "ways to analyze",
  "ways to study",
  "ways to practice",
  "useful information on",
  "detailed facts about",
  "complete information for",
  "everything you should know about",
  "step by step guide for",
  "stepwise explanation of",
  "full tutorial on",
  "detailed guide to",
  "how to approach",
  "how to handle",
  "how to deal with",
  "how to overcome",
  "common problems in",
  "frequent issues with",
  "typical mistakes in",
  "usual errors in",
  "main challenges in",
  "critical issues in",
  "common misconceptions about",
  "important tips for",
  "practical advice on",
  "expert tips on",
  "step by step method for",
  "full method to",
  "complete method to",
  "complete instructions for",
  "detailed instructions for",
  "how to execute",
  "how to perform",
  "how to run",
  "how to organize",
  "how to structure",
  "how to plan",
  "how to design",
  "how to develop",
  "how to prepare",
  "how to implement effectively",
  "best practices for",
  "recommended steps for",
  "recommended method to",
  "stepwise guide to",
  "easy guide to",
  "simple explanation for",
  "detailed overview of",
  "full overview of",
  "complete overview for",
  "the",
  "a",
  "an",
  "that",
  "this",
  "those",
  "these",
  "my",
  "your",
  "our",
  "their",
  "his",
  "her",
  "its",
  "each",
  "every",
  "some",
  "any",
  "few",
  "several",
  "many",
  "much",
  "the way to",
  "the steps to",
  "the process of",
  "the types of",
  "the kind of",
  "the method of",
  "the purpose of",
  "the meaning of",
  "the reason for",
  "the history of",
  "the function of",
  "the role of",
  "the definition for",
  "the examples of",
  "the list of",
  "the guide to",
  "the tutorial on",
  "the introduction to",
  "the basics of",
  "the principles of",
  "the fundamentals of",
  "the origin of",
  "the background of",
  "the description of",
  "the explanation of",
  "the overview of",
  "the summary of",
  "the steps in",
  "the uses of",
  "the benefits of",
  "the advantages of",
  "the disadvantages of",
  "the importance of",
  "the significance of",
  "the impact of",
  "the results of",
  "the causes of",
  "the effects of",
  "the process in",
  "the method in",
  "the part of",
  "the phase of",
  "the meaning for",
  "the difference between",
  "the relationship between",
  "the comparison between",
  "the connection between",
  "the link between",
  "the study of",
  "the field of",
  "the branch of",
  "the topic of",
  "the subject of",
  "the theory of",
  "the law of",
  "the rule of",
  "the concept of",
  "the idea of",
  "the example of",
  "the function in",
  "the formula for",
  "the equation for",
  "the explanation for",
  "the story of",
  "the event of",
  "the cause of",
  "the effect of",
  "the result of",
  "the outcome of",
  "the fact about",
  "the truth about",
  "the information on",
  "the detail of",
  "the reason behind",
  "the purpose behind",
  "the aim of",
  "the goal of",
  "the objective of",
  "the mission of",
  "the vision of",
  "the invention of",
  "the discovery of",
  "the creation of",
  "the structure of",
  "the design of",
  "the framework of",
  "the layout of",
  "the architecture of",
  "the steps involved in",
  "the stages of",
  "the sequence of",
  "the order of",
  "the pattern of",
  "the system of",
  "the mechanism of",
  "the operation of",
  "the function behind",
  "the importance for",
  "the process behind",
  "the significance for",
  "the guide for",
  "the tips for",
  "the tricks for",
  "the methods for",
  "the solutions for",
  "the ideas for",
  "the suggestions for",
  "the key points of",
  "the main points of",
  "the highlights of",
  "the summary for",
  "the explanation behind",
  "the reasons behind",
  "a process of",
  "a method of",
  "a technique for",
  "a way to",
  "a type of",
  "a kind of",
  "a form of",
  "a system of",
  "a rule of",
  "a concept of",
  "a principle of",
  "a theory of",
  "a model of",
  "a description of",
  "a guide to",
  "a tutorial on",
  "a manual for",
  "a plan for",
  "a strategy for",
  "a step in",
  "a reason for",
  "a cause of",
  "a function of",
  "a use of",
  "a purpose of",
  "a way of",
  "a process in",
  "a meaning of",
  "a difference between",
  "a comparison between",
  "a connection between",
  "a study of",
  "a background of",
  "a brief guide to",
  "a quick guide to",
  "a simple guide to",
  "a full explanation of",
  "a detailed explanation of",
  "a short meaning of",
  "a simple meaning of",
  "a brief description of",
  "a simple description of",
  "a short explanation of",
  "a simple definition of",
  "a complete guide to",
  "a detailed guide to",
  "a full tutorial on",
  "a quick explanation of",
  "a detailed description of",
  "that type of",
  "that kind of",
  "that way to",
  "that process of",
  "that method of",
  "that function of",
  "that example of",
  "that way of",
  "that form of",
  "that reason for",
  "that cause of",
  "that meaning of",
  "that step in",
  "that topic of",
  "that subject of",
  "that definition of",
  "that description of",
  "that explanation of",
  "this process of",
  "this method of",
  "this way to",
  "this example of",
  "this guide to",
  "this tutorial on",
  "this description of",
  "this definition of",
  "this type of",
  "this kind of",
  "this meaning of",
  "this purpose of",
  "this reason for",
  "this technique for",
  "this process in",
  "those examples of",
  "those types of",
  "those kinds of",
  "those ways to",
  "those steps to",
  "those methods for",
  "these examples of",
  "these types of",
  "these kinds of",
  "these ways to",
  "these steps to",
  "these methods for",
  "is there a",
  "is there any",
  "is there the",
  "is this a",
  "is this the",
  "is that a",
  "is that the",
  "are there any",
  "are there some",
  "can you tell me the",
  "can you explain the",
  "can you describe the",
  "can you define the",
  "can you show me the",
  "can you give me the",
  "could you tell me the",
  "could you explain the",
  "could you describe the",
  "should I use the",
  "should I follow the",
  "should we use the",
  "should we follow the",
  "what about the",
  "what about this",
  "what about that",
  "what about these",
  "what about those",
  "tell me the",
  "show me the",
  "explain the",
  "describe the",
  "define the",
  "give me the",
  "teach me the",
  "help me understand the",
  "help me learn the",
  "explain what",
  "explain how",
  "explain why",
  "define what",
  "describe what",
  "describe how",
  "teach me about",
  "tell me how to",
  "tell me why",
  "tell me when",
  "tell me where",
  "learn about the",
  "learn the process of",
  "learn the steps of",
  "understand the",
  "understand how",
  "understand why",
  "understand what",
  "understand the meaning of",
  "find out the",
  "discover the",
  "know the meaning of",
  "know how to",
  "know what is",
  "know when to",
  "know why to",
  "know where to",
  "understanding the",
  "understanding what is",
  "learning about the",
  "learning the process of",
  "learning how to",
  "learning the meaning of",
  "examples like",
  "topics like",
  "things like",
  "concepts like",
  "ideas like",
  "processes like",
  "methods like",
  "steps like",
  "systems like",
  "ways like"
];
